In [3]:
import numpy as np
import pandas as pd

print("Hello world")
i = 10
a = "Add something"
b = [20, 30, 40]
c = (1, 2, 3)
print(i)
print(a)
b.append(50)
employees = {"name": "John", "age": 25}
print(employees["name"])

for item in b:
    if item > 30:
        print("i is greater than 30")
    else:
        print("i is not greater than 30")
print("Goodbye world")

def greet(name = "world"):
    return f"Hello, {name}!"
print(greet(employees["name"]))

print(np.array(b))
print(pd.DataFrame([employees]))
print(np.version)
#Create a 1D array of numbers from 10 to 19.
array_1d = np.arange(10, 20)
#Create a 5×5 array filled with zeros, and a 3×3 identity matrix.
array_zeros = np.zeros((5, 5))
identity_matrix = np.identity(3)
print("5x5 Array of Zeros:")
print(array_zeros)

print("\n3x3 Identity Matrix:")
print(identity_matrix)

Hello world
10
Add something
John
i is not greater than 30
i is not greater than 30
i is greater than 30
i is greater than 30
Goodbye world
Hello, John!
[20 30 40 50]
   name  age
0  John   25
<module 'numpy.version' from '/opt/miniconda3/lib/python3.13/site-packages/numpy/version.py'>
5x5 Array of Zeros:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
random_integers = np.random.randint(1, 101, size=10)
print(random_integers)

[ 69  89  79  64  33  70 100  66  43  23]


In [29]:
arr = np.array([4, 9, 16, 25])
# arr = arr + 5
# print(arr)
#Compute element-wise square root and power.
sqrt_arr = np.sqrt(arr)
power_arr = np.power(arr, 2)
print("Element-wise Square Root:")
print(sqrt_arr)
print("Element-wise Power (squared):")
print(power_arr)

# Extract all even numbers from arr.
even_numbers = arr[arr % 2 != 0]
print("Even Numbers:")
print(even_numbers)
# Replace all numbers greater than 10 with -1.
arr[arr > 10] = -1
print("Array after replacing numbers greater than 10 with -1:")
print(arr)
# Reverse an array
reversed_arr = arr[::-1]
print("Reversed Array:")   
print(reversed_arr)
# Reverse an array without using [::-1]
reversed_arr_alt = np.flip(arr)
print("Reversed Array (using np.flip):")
print(reversed_arr_alt)

Element-wise Square Root:
[2. 3. 4. 5.]
Element-wise Power (squared):
[ 16  81 256 625]
Even Numbers:
[ 9 25]
Array after replacing numbers greater than 10 with -1:
[ 4  9 -1 -1]
Reversed Array:
[-1 -1  9  4]
Reversed Array (using np.flip):
[-1 -1  9  4]


In [41]:
array_1d_25 = np.arange(1,26)
print(array_1d_25)
#Reshape it into a 5×5 matrix.  
matrix_5x5 = array_1d_25.reshape(5, 5)
print(matrix_5x5)
flat_matrix = matrix_5x5.flatten()
print(flat_matrix)
#Find the maximum and minimum values in the matrix.
max_value = matrix_5x5.max()
min_value = matrix_5x5.min()
print("Maximum Value in the Matrix:", max_value)
print("Minimum Value in the Matrix:", min_value)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Maximum Value in the Matrix: 25
Minimum Value in the Matrix: 1


In [54]:
random_normal = np.random.normal(loc=50, scale=100, size=10)
print(random_normal)
# Find mean, median, standard deviation, min, max.
mean_value = np.mean(random_normal)
median_value = np.median(random_normal)
std_deviation = np.std(random_normal)
min_value = np.min(random_normal)
max_value = np.max(random_normal)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value) 

[170.63050868 -76.84094439  50.4821332   25.85522117 109.18252805
 -39.17868232 155.34765029  45.33721006 -38.4545151  -27.4222548 ]
Mean: 37.49388548490826
Median: 35.59621561922197
Standard Deviation: 81.27312188309571
Minimum Value: -76.8409443851264
Maximum Value: 170.6305086777612


In [4]:
# Create two 3x3 matrices
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Multiply using @ operator
result_at = matrix_a @ matrix_b
print("Result using @ operator:")
print(result_at)

# Multiply using np.dot
result_dot = np.dot(matrix_a, matrix_b)
print("Result using np.dot:")
print(result_dot)
# Compute transpose and determinant.
transpose_a = np.transpose(matrix_a)
determinant_a = np.linalg.det(matrix_a)
print("Transpose of Matrix A:")     
print(transpose_a)
print("Determinant of Matrix A:")
print(determinant_a)

Result using @ operator:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Result using np.dot:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of Matrix A:
-9.51619735392994e-16
